// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.TestApp = (function(_super) {

    __extends(TestApp, _super);

    function TestApp() {
      return TestApp.__super__.constructor.apply(this, arguments);
    }

    TestApp.prototype.properties = {
      FirstName: "Text",
      LastName: "Text",
      CategoryFilter: "Text"
    };

    TestApp.prototype.has_many = {
      Todos: "Todo",
      Categories: "Category"
    };

    TestApp.prototype.defaults = {
      FirstName: ""
    };

    TestApp.prototype.FullName = function() {
      return "" + (this.get('FirstName')) + " " + (this.get('LastName'));
    };

    TestApp.prototype.createTodo = function(formData) {
      return this.get("Todos").push(new Todo(formData));
    };

    TestApp.prototype.createCategory = function(formData) {
      return this.get("Categories").push(new Category(formData));
    };

    TestApp.prototype.FilteredTodos = function() {
      if (this.get("CategoryFilter").length) {
        console.log("got a filter");
        return this.get("Todos").filter("Category", this.get("CategoryFilter"));
      }
      return this.get("Todos");
    };

    return TestApp;

  })(Cydr.Controller);

  this.Todo = (function(_super) {

    __extends(Todo, _super);

    function Todo() {
      return Todo.__super__.constructor.apply(this, arguments);
    }

    Todo.prototype.properties = {
      Title: "Text",
      IsDone: "Boolean",
      Category: "Text"
    };

    Todo.prototype.defaults = {
      Title: "New todo"
    };

    Todo.prototype.Status = function() {
      if (this.get("IsDone")) {
        return "done";
      } else {
        return "open";
      }
    };

    Todo.prototype.Categories = function() {
      return App.get("Categories");
    };

    return Todo;

  })(Cydr.Model);

  this.Category = (function(_super) {

    __extends(Category, _super);

    function Category() {
      return Category.__super__.constructor.apply(this, arguments);
    }

    Category.prototype.properties = {
      Title: "Text"
    };

    return Category;

  })(Cydr.Model);

  window.App = new TestApp("body");

  App.get("Todos").push(new Todo({
    Title: "Shitty",
    IsDone: false,
    Category: "One"
  }));

  App.get("Todos").push(new Todo({
    Title: "Bitty",
    IsDone: false,
    Category: "One"
  }));

  App.get("Todos").push(new Todo({
    Title: "Litty",
    IsDone: false,
    Category: "Two"
  }));

  App.get("Categories").push(new Todo({
    Title: "One"
  }));

  App.get("Categories").push(new Todo({
    Title: "Two"
  }));

  App.get("Categories").push(new Todo({
    Title: "Three"
  }));

}).call(this);
